CREATE OR ALTER PROCEDURE GetAllRamProducts
AS
    SELECT NAME, MANUFACTURER, TYPE, VOLUME,
           FREQUENCY, VOLTAGE, PHOTO, COST, NEW_COST "NewCost",
           CURRENCY, DATE_ADDED "DateAdded" FROM RAM_PRODUCT;
GO;

CREATE OR ALTER PROCEDURE GetAllRamProductsInCurrency @InCurrencyIsoName nvarchar(3)
AS
    SELECT NAME, MANUFACTURER, TYPE, VOLUME,
           FREQUENCY, VOLTAGE, PHOTO,
           COST * (SELECT ISNULL(MULTIPLIER, 1) FROM CURRENCY_CONVERSION WHERE FROM_CURRENCY = RP.CURRENCY AND TO_CURRENCY = @InCurrencyIsoName) "Cost",
           NEW_COST * (SELECT ISNULL(MULTIPLIER, 1) FROM CURRENCY_CONVERSION WHERE FROM_CURRENCY = RP.CURRENCY AND TO_CURRENCY = @InCurrencyIsoName) "NewCost",
           @InCurrencyIsoName "Currency",
           DATE_ADDED "DateAdded" FROM RAM_PRODUCT RP;
GO;

CREATE OR ALTER PROCEDURE GetRamProductByNameInCurrency @Name nvarchar(100), @InCurrencyIsoName nvarchar(3)
AS
    SELECT NAME, MANUFACTURER, TYPE, VOLUME,
           FREQUENCY, VOLTAGE, PHOTO,
           COST * (SELECT ISNULL(MULTIPLIER, 1) FROM CURRENCY_CONVERSION WHERE FROM_CURRENCY = RP.CURRENCY AND TO_CURRENCY = @InCurrencyIsoName) "Cost",
           NEW_COST * (SELECT ISNULL(MULTIPLIER, 1) FROM CURRENCY_CONVERSION WHERE FROM_CURRENCY = RP.CURRENCY AND TO_CURRENCY = @InCurrencyIsoName) "NewCost",
           @InCurrencyIsoName "Currency",
           DATE_ADDED "DateAdded" FROM RAM_PRODUCT RP WHERE NAME = @Name;
GO;

CREATE OR ALTER PROCEDURE GetRamProductByName @Name nvarchar(100)
AS
    SELECT NAME, MANUFACTURER, TYPE, VOLUME,
           FREQUENCY, VOLTAGE, PHOTO,
           COST, NEW_COST "NewCost", CURRENCY,
           DATE_ADDED "DateAdded" FROM RAM_PRODUCT WHERE NAME = @Name;
GO;

CREATE OR ALTER PROCEDURE GetAllManufacturers
AS
    SELECT DISTINCT MANUFACTURER FROM RAM_PRODUCT ORDER BY MANUFACTURER;
GO;